// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const envKeys = Object.keys(process.env).filter(k => 
  k.includes('URL') || k.includes('POSTGRES') || k.includes('PRISMA') || k.includes('STORAGE') || k.includes('DB')
);
console.log('--- VERCEL ENV VARIABLES DEBUG ---');
console.log('Found these database-related keys: ', envKeys);
console.log('--- END DEBUG ---');

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL || process.env.STORAGE_URL || process.env.POSTGRES_PRISMA_URL || process.env.POSTGRES_URL,
  },
});
